on: [push, pull_request]

name: Docker

jobs:
  docker:
    name: Build and push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sulfurf/hello-action
          tag_with_sha: true
          tag_with_ref: true

